/*
 * Talknow API
 * This is a prototype of Talknow Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MessageDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversationDTO
 */
public class ConversationDTOTest {
    private final ConversationDTO model = new ConversationDTO();

    /**
     * Model tests for ConversationDTO
     */
    @Test
    public void testConversationDTO() {
        // TODO: test ConversationDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'contactPseudo'
     */
    @Test
    public void contactPseudoTest() {
        // TODO: test contactPseudo
    }

    /**
     * Test the property 'contactAvatar'
     */
    @Test
    public void contactAvatarTest() {
        // TODO: test contactAvatar
    }

    /**
     * Test the property 'lastMessage'
     */
    @Test
    public void lastMessageTest() {
        // TODO: test lastMessage
    }

    /**
     * Test the property 'lastMessageDate'
     */
    @Test
    public void lastMessageDateTest() {
        // TODO: test lastMessageDate
    }

    /**
     * Test the property 'myMessages'
     */
    @Test
    public void myMessagesTest() {
        // TODO: test myMessages
    }

}
