/*
 * Talknow API
 * This is a prototype of Talknow Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserInfoDTO
 */
public class UserInfoDTOTest {
    private final UserInfoDTO model = new UserInfoDTO();

    /**
     * Model tests for UserInfoDTO
     */
    @Test
    public void testUserInfoDTO() {
        // TODO: test UserInfoDTO
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'secondName'
     */
    @Test
    public void secondNameTest() {
        // TODO: test secondName
    }

    /**
     * Test the property 'adress'
     */
    @Test
    public void adressTest() {
        // TODO: test adress
    }

    /**
     * Test the property 'birthdayDate'
     */
    @Test
    public void birthdayDateTest() {
        // TODO: test birthdayDate
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

}
